### ISSUE TITLE
Application syntax

### ISSUE THREAD

**Issue by heysokam** [Niminem/Py2Nim#1]
What am I supposed to be doing exactly?
```
[sokam@nox tool]$ ls
layoutString.py  py2nim  random.py  rng.nim
[sokam@nox tool]$ py2nim layoutString.py python
py2nim.nim(13)           translate
Error: unhandled exception: Unable to parse python module. Response:  [ModuleError]
[sokam@nox tool]$ python
python             python2.7          python2-config     python3.10         python3-config
python2            python2.7-config   python3            python3.10-config  python-config
```
Is this some syntax on my file that conflicts with the translator, or am I calling the app wrong?

**Comment by Niminem** [comment]
@heysokam Working on the fix now, nimble doesn't install the .py and .nims file from the source directory.

Also, this is extremely early on with this tool. We have very little functionality right now. Will be posting the list of current functionality shortly.

**Comment by Niminem** [comment]
@heysokam update py2nim to it's latest version (0.1.2) and you should be good to go man!

I will be creating documentation, listing all features, roadmap by EOW
